[CmdletBinding()]
param(
  [string]$HostAddress = "127.0.0.1",
  [int]$Port = 9191,
  [switch]$SkipInstall,
  [switch]$SkipBuild
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function New-RandomSecret([int]$Bytes = 48) {
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $buf = New-Object byte[] $Bytes
    $rng.GetBytes($buf)
    $s = [Convert]::ToBase64String($buf).TrimEnd('=')
    $s = $s.Replace('+','-').Replace('/','_')
    return $s
  } finally {
    $rng.Dispose()
  }
}

function Ensure-SessionSecret([string]$Root) {
  $localEnv = Join-Path $Root "local.env.ps1"

  if (Test-Path -Path $localEnv) {
    . $localEnv
  }

  if ([string]::IsNullOrWhiteSpace($env:DLT_SESSION_SECRET) -or $env:DLT_SESSION_SECRET.Length -lt 32) {
    $secret = New-RandomSecret
    $content = @(
      "# Generated by install-and-run.ps1",
      "# Keep this file private.",
      "`$env:DLT_SESSION_SECRET = '$secret'"
    ) -join "`r`n"
    Set-Content -Path $localEnv -Value ($content + "`r`n") -Encoding UTF8
    . $localEnv
  }
}

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot ".." )).Path
Set-Location $repoRoot

Ensure-SessionSecret -Root $repoRoot

if (-not $SkipInstall) {
  Write-Host "==> npm install" -ForegroundColor Cyan
  npm install --workspaces --include-workspace-root
}

if (-not $SkipBuild) {
  Write-Host "==> npm run build" -ForegroundColor Cyan
  npm run build
}

$env:HOST = $HostAddress
$env:PORT = "$Port"

Write-Host "==> Starting backend on http://${HostAddress}:${Port}" -ForegroundColor Cyan
npm run -w backend start
