[CmdletBinding()]
param(
  [string]$ZipPath = "./DLT-offline-latest.zip",
  [string]$InstallDir = "",
  [switch]$NoStart
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($InstallDir)) {
  # Default to a relative install folder next to this script (or current dir if unknown).
  $base = $PSScriptRoot
  if ([string]::IsNullOrWhiteSpace($base)) { $base = (Get-Location).Path }
  $InstallDir = Join-Path $base "DLT"
}

function Write-Step([string]$Title) {
  Write-Host "==> $Title" -ForegroundColor Cyan
}

function New-RandomSecret([int]$Bytes = 48) {
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $buf = New-Object byte[] $Bytes
    $rng.GetBytes($buf)
    # Base64url
    $s = [Convert]::ToBase64String($buf).TrimEnd('=')
    $s = $s.Replace('+','-').Replace('/','_')
    return $s
  } finally {
    $rng.Dispose()
  }
}

$resolvedZip = (Resolve-Path -Path $ZipPath).Path
if (-not (Test-Path -Path $InstallDir)) {
  New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
}
$installRoot = (Resolve-Path -Path $InstallDir).Path

Write-Step "Extract bundle to a temp folder"
$tempRoot = Join-Path $env:TEMP ("DLT-install-" + (Get-Date).ToString('yyyyMMdd-HHmmss'))
New-Item -ItemType Directory -Force -Path $tempRoot | Out-Null
Expand-Archive -Path $resolvedZip -DestinationPath $tempRoot -Force

# Bundle zip contains a single folder at the root.
$bundleFolder = Get-ChildItem -Path $tempRoot -Directory | Select-Object -First 1
if (-not $bundleFolder) {
  throw "Invalid bundle: no folder found in zip root."
}
$bundlePath = $bundleFolder.FullName

Write-Step "Extract app into install folder"
# No robocopy. No mirroring. Just extract.
Expand-Archive -Path $resolvedZip -DestinationPath $installRoot -Force

# App root is the single folder that came out of the zip.
$appRoot = Join-Path $installRoot (Split-Path -Leaf $bundlePath)
if (-not (Test-Path -Path $appRoot)) {
  # Fallback: if zip layout changes, assume install root is app root.
  $appRoot = $installRoot
}

Write-Step "Ensure local secrets exist"
$localEnv = Join-Path $appRoot "local.env.ps1"
if (-not (Test-Path $localEnv)) {
  $secret = New-RandomSecret
  $content = @(
    "# Generated by install-offline.ps1",
    "# Keep this file private.",
    "`$env:DLT_SESSION_SECRET = '$secret'"
  ) -join "`r`n"
  Set-Content -Path $localEnv -Value ($content + "`r`n") -Encoding UTF8
}

Write-Host "" 
Write-Host "Installed to: $appRoot" -ForegroundColor Green
Write-Host "Next: run .\\run.ps1" -ForegroundColor Green

if (-not $NoStart) {
  Write-Step "Starting backend"
  Push-Location $appRoot
  Start-Process -FilePath powershell -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File .\\start-backend.ps1" | Out-Null
  Pop-Location
}
