[CmdletBinding()]
param(
  [string]$ZipPath = "./DLT-offline-latest.zip",
  [string]$InstallDir = "C:\DLT",
  [switch]$NoStart
)

$ErrorActionPreference = "Stop"

function Write-Step([string]$Title) {
  Write-Host "==> $Title" -ForegroundColor Cyan
}

function New-RandomSecret([int]$Bytes = 48) {
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $buf = New-Object byte[] $Bytes
    $rng.GetBytes($buf)
    # Base64url
    $s = [Convert]::ToBase64String($buf).TrimEnd('=')
    $s = $s.Replace('+','-').Replace('/','_')
    return $s
  } finally {
    $rng.Dispose()
  }
}

$resolvedZip = (Resolve-Path -Path $ZipPath).Path
$installRoot = (Resolve-Path -Path $InstallDir -ErrorAction SilentlyContinue)
if (-not $installRoot) {
  New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
  $installRoot = (Resolve-Path -Path $InstallDir).Path
}

Write-Step "Extract bundle to a temp folder"
$tempRoot = Join-Path $env:TEMP ("DLT-install-" + (Get-Date).ToString('yyyyMMdd-HHmmss'))
New-Item -ItemType Directory -Force -Path $tempRoot | Out-Null
Expand-Archive -Path $resolvedZip -DestinationPath $tempRoot -Force

# Bundle zip contains a single folder at the root.
$bundleFolder = Get-ChildItem -Path $tempRoot -Directory | Select-Object -First 1
if (-not $bundleFolder) {
  throw "Invalid bundle: no folder found in zip root."
}
$bundlePath = $bundleFolder.FullName

Write-Step "Preserve existing config/data if present"
$preserve = Join-Path $tempRoot "preserve"
New-Item -ItemType Directory -Force -Path $preserve | Out-Null

$existingConfig = Join-Path $installRoot "config.json"
if (Test-Path $existingConfig) {
  Copy-Item -Force $existingConfig (Join-Path $preserve "config.json")
}

$existingBackendData = Join-Path $installRoot "backend\data"
if (Test-Path $existingBackendData) {
  robocopy $existingBackendData (Join-Path $preserve "backend-data") /MIR /NFL /NDL /NJH /NJS /NP | Out-Null
}

$existingRootData = Join-Path $installRoot "data"
if (Test-Path $existingRootData) {
  robocopy $existingRootData (Join-Path $preserve "root-data") /MIR /NFL /NDL /NJH /NJS /NP | Out-Null
}

Write-Step "Install (copy files into place)"
robocopy $bundlePath $installRoot /MIR /NFL /NDL /NJH /NJS /NP | Out-Null

if (Test-Path (Join-Path $preserve "config.json")) {
  Copy-Item -Force (Join-Path $preserve "config.json") $existingConfig
}

if (Test-Path (Join-Path $preserve "backend-data")) {
  New-Item -ItemType Directory -Force -Path (Join-Path $installRoot "backend\data") | Out-Null
  robocopy (Join-Path $preserve "backend-data") (Join-Path $installRoot "backend\data") /MIR /NFL /NDL /NJH /NJS /NP | Out-Null
}

if (Test-Path (Join-Path $preserve "root-data")) {
  New-Item -ItemType Directory -Force -Path (Join-Path $installRoot "data") | Out-Null
  robocopy (Join-Path $preserve "root-data") (Join-Path $installRoot "data") /MIR /NFL /NDL /NJH /NJS /NP | Out-Null
}

Write-Step "Ensure local secrets exist"
$localEnv = Join-Path $installRoot "local.env.ps1"
if (-not (Test-Path $localEnv)) {
  $secret = New-RandomSecret
  $content = @(
    "# Generated by install-offline.ps1",
    "# Keep this file private.",
    "`$env:DLT_SESSION_SECRET = '$secret'"
  ) -join "`r`n"
  Set-Content -Path $localEnv -Value ($content + "`r`n") -Encoding UTF8
}

Write-Host "" 
Write-Host "Installed to: $installRoot" -ForegroundColor Green
Write-Host "Next: run .\\start-backend.ps1" -ForegroundColor Green

if (-not $NoStart) {
  Write-Step "Starting backend"
  Push-Location $installRoot
  Start-Process -FilePath powershell -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File .\\start-backend.ps1" | Out-Null
  Pop-Location
}
