[CmdletBinding()]
param(
  [string]$HostAddress = $env:DLT_HOST,
  [int]$Port = 9191
)

$ErrorActionPreference = "Stop"

function New-RandomSecret([int]$Bytes = 48) {
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $buf = New-Object byte[] $Bytes
    $rng.GetBytes($buf)
    $s = [Convert]::ToBase64String($buf).TrimEnd('=')
    $s = $s.Replace('+','-').Replace('/','_')
    return $s
  } finally {
    $rng.Dispose()
  }
}

$root = $PSScriptRoot

if ([string]::IsNullOrWhiteSpace($HostAddress)) {
  $HostAddress = "127.0.0.1"
}

# Prefer a bundled portable Node if present; otherwise fall back to system node.
$nodeCandidates = @(
  (Join-Path $root "node\\node.exe"),
  (Join-Path $root "runtime\\node\\node.exe"),
  (Join-Path $root "tools\\node\\node.exe")
)

$nodeExe = $null
foreach ($c in $nodeCandidates) {
  if (Test-Path -Path $c) { $nodeExe = $c; break }
}
if (-not $nodeExe) {
  $cmd = Get-Command node -ErrorAction SilentlyContinue
  if ($cmd) { $nodeExe = $cmd.Source }
}
if (-not $nodeExe) {
  Write-Error "Node.js not found. Install Node.js or place a portable node.exe at .\\node\\node.exe"
  exit 1
}

# Load or create local env (session secret).
$localEnv = Join-Path $root "local.env.ps1"
if (Test-Path -Path $localEnv) {
  . $localEnv
}
if ([string]::IsNullOrWhiteSpace($env:DLT_SESSION_SECRET) -or $env:DLT_SESSION_SECRET.Length -lt 32) {
  $secret = New-RandomSecret
  $content = @(
    "# Generated by run.ps1",
    "# Keep this file private.",
    "`$env:DLT_SESSION_SECRET = '$secret'"
  ) -join "`r`n"
  Set-Content -Path $localEnv -Value ($content + "`r`n") -Encoding UTF8
  . $localEnv
}

$env:PORT = "$Port"
$env:HOST = $HostAddress

$backendDir = Join-Path $root "backend"
$entry = Join-Path $backendDir "dist\\index.js"
if (-not (Test-Path -Path $entry)) {
  Write-Error "Missing backend\\dist\\index.js. This doesn't look like a built offline bundle."
  exit 1
}

Write-Host "Starting DLT backend on http://${HostAddress}:${Port} ..."
Push-Location $backendDir
try {
  & $nodeExe $entry
} finally {
  Pop-Location
}
